[phases.setup]
nixPkgs = ["python3", "python3-pip", "ffmpeg", "git", "curl"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = [
  "pip3 install -q --no-cache-dir yt-dlp",
  "yt-dlp --version"
]

[start]
cmd = "node index.js"
