[phases.setup]
nixPkgs = ["python3", "python3Packages.pip", "ffmpeg", "git", "curl"]

[phases.install]
cmds = ["npm install --production"]

[phases.build]
cmds = [
  "python3 -m pip install -q --no-cache-dir yt-dlp",
  "yt-dlp --version"
]

[start]
cmd = "node index.js"
